export default {
  FETCH_USER: "FETCH_USER",
  LOAD_APPLICATION_REQUEST: " LOAD_APPLICATIONS_REQUEST",
  LOAD_APPLICATION_SUCCESS: " LOAD_APPLICATIONS_SUCCESS",
  LOAD_APPLICATION_FAILED: " LOAD_APPLICATIONS_FAILED",
  UPDATE_APPLICATION_REQUEST: " UPDATE_APPLICATIONS_REQUEST",
  UPDATE_APPLICATION_SUCCESS: " UPDATE_APPLICATIONS_SUCCESS",
  UPDATE_APPLICATION_FAILED: " UPDATE_APPLICATIONS_FAILED"
}
